export const SET_USER='set_user'
export const SET_WAITLIST='set_waitlist'
export const SET_TABLELIST='set_tablelist'
export const BOOK_TABLE='book_table'
export const VACATE_TABLE='vacate_table'
export const UPDATE_TABLE='update_table'
export const ADD_TO_WAITLIST='add_to_waitlist'